---
title: "initial eda"
author: "margaret"
date: "4/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-pkgs}
library(tidyverse)
library(spotifyr)
library(billboard)
```

```{r data}
access_token <- get_spotify_access_token()
```

```{r}
data1 <- spotify_track_data
data2 <- wiki_hot_100s

data <- full_join(
  spotify_track_data, wiki_hot_100s,
  by = c("artist_name" = "artist", "track_name" = "title")
)
```

```{r}
data2 <- data2 %>%
  mutate(
    featured = str_extract(title, "(?<=featuring ).*"),
    cleaned_track = 
      ifelse(str_detect(title, "featuring"), 
             str_extract(title, ".*( featuring*)"), title) %>%
      str_to_upper()
  )
data1 <- data1 %>%
  mutate(
    cleaned_track = track_name %>%
      str_replace("&", "and") %>%
      str_to_upper()
  )
data <- right_join(
  data1, data2,
  by = c("artist_name" = "artist", "cleaned_track" = "cleaned_track")
)
```

```{r}
data %>%
  drop_na(no) %>%
  group_by(artist_name) %>%
  summarize(
    mean_place = mean(as.numeric(no)),
    count = n(),
    most_recent = max(as.numeric(year.y))
  ) %>%
  filter(count > 5) %>%
  arrange(desc(count), desc(mean_place))
```

```{r}
track_data <- inner_join(
  data, 
  tracks,
  by = c("track_id" = "id")
)

big_data <- left_join(track_data, artists, by = c("artist_id" = "id"))
```

```{r}
track_data %>%
 filter(as.numeric(no) < 11 & popularity != "0") %>%
  ggplot(
    aes(
      x = as.numeric(year.x), y = as.numeric(popularity)
    )
  ) +
  geom_smooth() +
  geom_point()
```
```{r}
artist_year <- track_data %>%
  group_by(artist_id) %>%
  summarize(latest_release = max(as.numeric(year.x))) %>%
  inner_join(artists, by = c("artist_id" = "id")) %>%
  group_by(latest_release)
```

```{r}
genres <- artist_year %>%
  pull(genres) %>%
  flatten() %>%
  unlist() %>%
  tibble() %>%
  distinct()
```

```{r}
artist_year %>%
  pull(genres) %>%
  flatten() %>%
  unlist() %>%
  tibble() %>%
  rename("genre" = ".") %>%
  count(genre) %>%
  arrange(desc(n)) %>%
  slice(1:25) %>%
  ggplot(aes(y = fct_inorder(genre, n), x = n)) +
  geom_col()
```
```{r}
artist_year %>%
  pull(genres) %>%
  flatten() %>%
  unlist() %>%
  tibble() %>%
  rename("genre" = ".") %>%
  mutate(
    simple_genre = case_when(
      str_detect(genre, "pop") ~ "pop",
      str_detect(genre, "rock") ~ "rock",
      str_detect(genre, "r&b") | str_detect(genre, "rhythm and blues") ~ "r&b",
      str_detect(genre, "soul") ~ "soul",
      str_detect(genre, "country") ~ "country",
      str_detect(genre, "punk") ~ "punk",
      str_detect(genre, "jazz") ~ "jazz",
      str_detect(genre, "folk") ~ "folk",
      str_detect(genre, "rap") ~ "rap",
      str_detect(genre, "dance") ~ "dance",
      TRUE ~ "other"
    )
  ) %>%
  count(simple_genre) %>%
  arrange(desc(n)) %>%
  # slice(1:25) %>%
  ggplot(aes(y = fct_inorder(simple_genre, n), x = n)) +
  geom_col()
```
