---
title: "initial eda"
author: "margaret"
date: "4/4/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-pkgs}
library(tidyverse)
library(spotifyr)
library(billboard)
library(tidytext)
```

```{r data-token}
access_token <- get_spotify_access_token()
```

```{r read-data}
data1 <- spotify_track_data
data2 <- wiki_hot_100s
tracks <- read_csv("data/track_info.csv")
artists <- read_csv("data/artist_info.csv")
long_genres <- read_csv("data/artist_genres.csv")
data <- full_join(
  spotify_track_data, wiki_hot_100s,
  by = c("artist_name" = "artist", "track_name" = "title")
)
```

```{r data-clean}
data2 <- data2 %>%
  mutate(
    featured = str_extract(title, "(?<=featuring ).*"),
    cleaned_track = 
      ifelse(str_detect(title, "featuring"), 
             str_extract(title, ".*( featuring*)"), title) %>%
      str_to_upper()
  )
data1 <- data1 %>%
  mutate(
    cleaned_track = track_name %>%
      str_replace("&", "and") %>%
      str_to_upper()
  )
data <- right_join(
  data1, data2,
  by = c("artist_name" = "artist", "cleaned_track" = "cleaned_track")
)
```

```{r explore-pos}
data %>%
  drop_na(no) %>%
  group_by(artist_name) %>%
  summarize(
    mean_place = mean(as.numeric(no)),
    count = n(),
    most_recent = max(as.numeric(year.y))
  ) %>%
  filter(count > 5) %>%
  arrange(desc(count), desc(mean_place))
```

```{r more-data-clean}
track_data <- inner_join(
  data, 
  tracks,
  by = c("track_id" = "id")
)

big_data <- left_join(track_data, artists, by = c("artist_id" = "id"))
```

```{r plot1, cache = T}
track_data %>%
 filter(as.numeric(no) < 11 & popularity != "0") %>%
  ggplot(
    aes(
      x = as.numeric(year.x), y = as.numeric(popularity)
    )
  ) +
  geom_smooth(se = F) +
  geom_point() +
  labs(
    x = "Year",
    y = "Popularity in 2022",
    title = "Song popularity by year produced",
    subtitle = "As designated by spotify",
    caption = "Billboard top 100 songs"
  ) +
  theme_minimal()
```

```{r artist-year}
artist_year <- track_data %>%
  group_by(artist_id) %>%
  summarize(
    latest_release = max(as.numeric(year.x)),
    med_release = median(as.numeric(year.x))
    ) %>%
  inner_join(artists, by = c("artist_id" = "id")) %>%
  group_by(latest_release)
```

```{r genre-bar}
long_genres %>%
  rename("genre" = "genres") %>%
  count(genre) %>%
  arrange(desc(n)) %>%
  slice(1:25) %>%
  ggplot(aes(y = fct_inorder(genre, n), x = n)) +
  geom_col()
```

```{r simple-bar, cache = T}
long_genres %>%
  rename("genre" = "genres") %>%
  mutate(
    simple_genre = case_when(
      str_detect(genre, "pop") ~ "pop",
      str_detect(genre, "rock") ~ "rock",
      str_detect(genre, "r&b") | str_detect(genre, "rhythm and blues") ~ "r&b",
      str_detect(genre, "soul") ~ "soul",
      str_detect(genre, "country") ~ "country",
      str_detect(genre, "punk") ~ "punk",
      str_detect(genre, "jazz") ~ "jazz",
      str_detect(genre, "folk") ~ "folk",
      str_detect(genre, "rap") ~ "rap",
      str_detect(genre, "dance") ~ "dance",
      str_detect(genre, "disco") ~ "disco",
      str_detect(genre, "funk") ~ "funk",
      str_detect(genre, "hip hop") ~ "hip hop",
      TRUE ~ "other"
    )
  ) %>%
  count(simple_genre) %>%
  arrange(desc(n)) %>%
  ggplot(aes(y = fct_inorder(simple_genre, n), x = n)) +
  geom_col() +
  labs(
    x = "Frequency",
    y = "Genre",
    title = "Frequency of dfferent genres",
    subtitle = "By artist",
    caption = "Billboard top 100 songs"
  ) +
  theme_minimal()
```

```{r decade-genre, cache = T}
long_genres %>%
  mutate(
    simple_genre = case_when(
      str_detect(genres, "pop") ~ "pop",
      str_detect(genres, "rock") ~ "rock",
      str_detect(genres, "r&b") | str_detect(genres, "rhythm and blues") ~ "r&b",
      str_detect(genres, "soul") ~ "soul",
      str_detect(genres, "country") ~ "country",
      str_detect(genres, "rap") ~ "rap",
      str_detect(genres, "disco") ~ "disco",
      str_detect(genres, "hip hop") ~ "hip hop",
      TRUE ~ "other"
    )
  ) %>%
  select(-genres) %>%
  distinct() %>%
  mutate(
    decade = floor(med_release/10)*10,
    simple_genre = fct_other(fct_infreq(simple_genre), drop = c("other"))
  ) %>%
  count(decade, simple_genre) %>%
  ggplot(aes(x = n, y = as.factor(decade), fill = fct_rev(simple_genre))) +
  geom_col(position = "fill") +
  scale_fill_brewer(palette = "Set3", direction = -1) +
  labs(
    x = NULL, 
    y = "Decade", 
    fill = "Genre", 
    title = "Popularity of genres per artist over time",
    subtitle = "By decade",
    caption = "Billboard top 100 songs"
  ) +
  guides(fill = guide_legend(nrow = 1, reverse = T)) +
  theme_minimal() +
  theme(legend.position = "bottom", legend.direction = "horizontal")
```

```{r word-bar, cache = T}
track_data %>%
  select(year.x, artist_name, track_name, popularity, album.name) %>%
  unnest_tokens(word, track_name) %>%
  mutate(
    decade = as.factor(floor(as.numeric(year.x)/10)*10)
    ) %>%
  count(word, sort = TRUE) %>%
  anti_join(stop_words) %>%
  slice(1:10) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word)) +
  geom_col() +
  labs(
    y = "Word",
    x = "Frequency",
    title = "Frequency of the most common words in song titles",
    caption = "Billboard top 100 songs"
    ) +
  theme_minimal()
```

```{r decade-word, cache = T}
common_words <- track_data %>%
  select(year.x, artist_name, track_name, popularity, album.name) %>%
  unnest_tokens(word, track_name) %>%
  mutate(
    decade = as.factor(floor(as.numeric(year.x)/10)*10)
    ) %>%
  count(word, sort = TRUE) %>%
  anti_join(stop_words) %>%
  slice(1:8) %>%
  pull(word)

track_data %>%
  select(year.x, artist_name, track_name, popularity, album.name) %>%
  unnest_tokens(word, track_name) %>%
  mutate(
    decade = as.factor(floor(as.numeric(year.x)/10)*10),
    word = fct_infreq(word)
    ) %>%
  count(decade, word, sort = TRUE) %>%
  anti_join(stop_words) %>%
  filter(word %in% common_words) %>%
  ggplot(aes(x = n, y = decade, fill = fct_rev(word))) +
  geom_col(position = "fill") +
  scale_fill_brewer(palette = "Set3", direction = -1) +
  labs(
    y = "Decade",
    x = NULL,
    fill = "Word",
    title = "Frequency of the most common words in song titles",
    subtitle = "By decade",
    caption = "Billboard top 100 songs"
    ) +
  guides(fill = guide_legend(nrow = 1, reverse = T)) +
  theme_minimal() +
  theme(legend.position = "bottom", legend.direction = "horizontal")
```

```{r}
a <- track_data %>%
  filter( year.x == 1980, no == 1) %>%
  pull(track_name)

a[[1]]
```

